### ISSUE TITLE
Data format for NLI

### ISSUE THREAD

**Issue by strubell** [allenai/sledgehammer#1]
Could you provide some more details on the expected data format for sentence-pair classification (NLI) data? Is there any processing beyond concatenating the two sentences (e.g. a separator token)? Thanks!

**Comment by roys174** [comment]
Thanks Emma for raising this issue, and sorry for the late reply, somehow we've missed it. 

For NLI, please concatenate the premise and the hypothesis with another tab. I.e., "<label>\t<premise>\t<hypothesis>".

We added this to the main documentation. Please also note that we recently added a script for downloading all the datasets, which creates the dataset files in the correct format, including for SMLI and MultiNLI.
